version: '3.8'

services:
  nfc-app:
    # 建议生产环境直接拉取 GitHub 构建好的镜像
    image: ghcr.io/hsieh19/nfc-patrol-system:0.2.0
    build:
      context: .
      args:
        - DB_TYPE=mysql # 或者改为 sqlite
    container_name: nfc-patrol-system
    restart: always
    environment:
      - DATABASE_URL=mysql://root:password@172.17.0.1:3306/nfc_db
      - JWT_SECRET=your-production-secret-key-change-it
      # 这里填写你内网 Nginx 的 HTTPS 完整访问地址
      - NEXT_PUBLIC_BASE_URL=https://patrol.internal.com
    # 内部只跑 HTTP
    ports:
      - "3000:3000"
